### ISSUE TITLE
Build fails on ubuntu 16.04

### ISSUE THREAD

**Issue by wsnipex** [rbuehlma/pvr.zattoo#24]
packaging on ubuntu 16.04 currently fails:
https://launchpadlibrarian.net/392138110/buildlog_ubuntu-xenial-amd64.kodi-pvr-zattoo_18.0.53-1~xenial_BUILDING.txt.gz

**Comment by rbuehlma** [comment]
Would it be possible not to install "rapidjson-dev" with apt? I guess cmake would then download the right version of rapidjson. The one from Ubuntu 16.04 seems to be too old.

**Comment by rbuehlma** [comment]
Or could you try this one:
https://github.com/rbuehlma/pvr.zattoo/tree/rapidjson_min_version

**Comment by wsnipex** [comment]
> Would it be possible not to install "rapidjson-dev" with apt? I guess cmake would then download the right version of rapidjson. The one from Ubuntu 16.04 seems to be too old.

no, not possible

Requiring rapidjason 1.1 is possible, but there is no such package for ubuntu 16.04. Kodi itself requires 1.0.2 as minimum version

**Comment by rbuehlma** [comment]
> Requiring rapidjason 1.1 is possible, but there is no such package for ubuntu 16.04. Kodi itself requires 1.0.2 as minimum version

I guess this is no problem. cmake will download rapidjson 1.1 if it is not available. And as rapidjson are only header files, I do also not expect any version conflicts. Is it possible to test that branch or do I need to merge it to master?

**Comment by wsnipex** [comment]
No, cmake won't download anything when building on launchpad, since network access is _not allowed_

**Comment by rbuehlma** [comment]
I'm not sure how to fix this correctly. I changed the required version to 1.0.2 but how does this work for kodi if ubuntu 16.04 has an older version and during the build, nothing can be downloaded? Is there a way do provide the required version to launchpad? should I include the whole rapidjson in my repo?

**Comment by wsnipex** [comment]
launchpad always builds with the existing rapidjson-dev package.
Kodi builds fine with v1.0.2. Once kodi needs a higher version, I'll have to upload an appropriate version.
Do you really need 1.1?

**Comment by rbuehlma** [comment]
No, I guess v1.0.2 is fine as well. I did update this branch:
https://github.com/rbuehlma/pvr.zattoo/tree/rapidjson_min_version
(missed the commit message but will update that one as well prior merging).

Could you try if this one builds fine?

**Comment by wsnipex** [comment]
https://github.com/rbuehlma/pvr.zattoo/commit/0f7584fe9d4c352d30eedf577835185c41129e85 won't change anything. Rapidjson is already found:
-- Found RapidJSON: /usr/include (found version "1.0.2")

In order to fix the error you'd have to fix the offending code:
/<<PKGBUILDDIR>>/src/ZatData.cpp:1118:90: error: ‘const class rapidjson::GenericValue<rapidjson::UTF8<> >’ has no member named ‘GetArray’

**Comment by rbuehlma** [comment]
Ok, now GetArray is gone. Better?

**Comment by wsnipex** [comment]
yes, now it works for the rapidjson_min_version branch

**Comment by rbuehlma** [comment]
Thanks. I will runtime test the change later today and then merge it to master.

**Comment by rbuehlma** [comment]
Its now merged to the master. Thanks for your input
